[project]
name = "dictate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.120.0",
    "openvino>=2026.2.1",
    "optimum-intel>=2.0.0",
    "setuptools<81",
    "sounddevice>=0.5.5",
    "webrtcvad>=2.0.10",
]
